### ISSUE TITLE
show multiple places where the smartcard reader can be purchased 

### ISSUE THREAD

**Issue by stschmitt** [ibm-cloud-docs/hs-crypto#17]
Based on customer feedback the shown location does not ship the reader to all places.
The reader itself is not only available from this place. 
SPR332 v2.0 Secure Class 2 PIN Pad Reader could be bought at multiple other places.

We should at least mention the reader class, name and that it is available on other shops and may mention those shops

**Comment by TiffanyLiIBM** [comment]
@stschmitt I can't see which topic this issue was opened against, but I suppose you are referring to the FAQ: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-faq-provisioning-operations#faq-procure-smart-card.

We could include the reader class and name as you included in the issue. Could you let me know the shops that it is available so that we can include the info? Thanks!

**Comment by stschmitt** [comment]
SPR332 v2.0 Secure Class 2 PIN Pad Reader (part # 905127-1)

https://www.amazon.de/SPR332-Speed-Secure-Kartenleser-Online-Abrechnung/dp/B0092NGGWW
https://www.scm-pc-card.de/kartenleser/online-banking/101/spr332-v2
https://digifeat.com/product/spr332-v2-0/

**Comment by TiffanyLiIBM** [comment]
@stschmitt Hi Stefan, 

I have included the shopping info at: https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-prepare-management-utilities#ordering-smart-card-readers. Please take a look. Thanks!
