### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by hancockp-at-ibm** [ibm-cloud-docs/hs-crypto#31]
In https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-master-key-rotation-intro 
the link in this sentence 
`For detailed instructions, see [Rotating master keys by using key parts](https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-rotate-master-key-key-parts).`

is broken.

**Comment by TiffanyLiIBM** [comment]
Hi @hancockp-at-ibm,

Please find the updated doc at: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm#initialize-crypto-cli-next.
The link has been fixed to point to: https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-rotate-master-key-cli-key-part. Please close this issue if the problem is resolved. Thanks!

**Comment by TiffanyLiIBM** [comment]
No more comments received. Closing...

**Comment by hancockp-at-ibm** [comment]
@TiffanyLiIBM, Thank you. For some reason, I didn't get (or notice?) the notification about your earlier reply.
