### ISSUE TITLE
HSM initialisation by key part files : Needs document updates

### ISSUE THREAD

**Issue by vishwabmc** [ibm-cloud-docs/hs-crypto#38]
I am going through [TKE by key part files](https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm) and see it points to [pre-requisites](https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm-prerequisite) page. There, it shows  this. 

<img width="893" alt="Screenshot 2022-10-13 at 2 04 57 PM" src="https://user-images.githubusercontent.com/13940109/195545738-070f6521-2f36-4379-8a6a-3858bb219ff4.png">

 This expects the user to get to another link to login to IBM cloud, and the text below shows to point to the right target. So, in my view, it's not clear. It would be clean if we only gave the command here showing logging into IBM cloud too. Can the document be updated to contain this 

Best would be, if we could keep all this in [here itself](https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm)

At the least, [this-link](https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm) needs a `Pre-requisite` section. The way it is now.  it's right after the video and is very easy for someone to just miss it. 

<img width="818" alt="Screenshot 2022-10-13 at 2 08 40 PM" src="https://user-images.githubusercontent.com/13940109/195546728-c6df4dd9-57cc-4ea5-a2af-62dd0762d0d5.png">

Having its own section for pre-requisites would help make it clear.

**Comment by TiffanyLiIBM** [comment]
Hi @vishwabmcm,
Many thanks for providing comments to the docs.

I've updated the [Before you begin](https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm-prerequisite&interface=ui) topic to include the command to login to IBM Cloud:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/40377681/195795166-31fd8c6e-3e02-4bf7-bca0-19183dce7710.png">
And also, a section header is included in the [Initializing service instances using key part files](https://test.cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-initialize-hsm&interface=ui#initialize-hsm-cli-prerequisite)  topic so that the prerequisite is standout.
<img width="631" alt="image" src="https://user-images.githubusercontent.com/40377681/195795514-b3833481-0327-4f4a-abe8-dc8d3feed4ab.png">

Since the Before you begin topic info is used across all service initialization approaches, we didn't include it in a single topic for easy maintenance. Hope it makes sense.

Please review and let us know if you have additional comments. Thanks!

**Comment by TiffanyLiIBM** [comment]
No more comments received. Closing...
