### ISSUE TITLE
Weird phrasing on IBM HPCS page

### ISSUE THREAD

**Issue by rossheninger** [ibm-cloud-docs/hs-crypto#4]
https://www.ibm.com/cloud/hyper-protect-crypto

At the above link this is the first sentence:
```IBM Cloud™ Hyper Protect Crypto Services is a key management and cloud hardware security module (HSM).```

I'm not sure, this isn't my area of expertise but the phrasing seems weird, and it doesn't match the cloud catalog description which is:
```IBM Cloud Hyper Protect Crypto Services is a dedicated key management service and hardware security module (HSM).```

It seems like it is missing a few words or something. The grammar is clunky. Maybe it could be changed to:
```IBM Cloud™ Hyper Protect Crypto Services is a dedicated key management and cloud hardware security module (HSM) service.```

If you removed the "key management and" in the first example or the "dedicated key management service" in the second example, the sentence would be:
```IBM Cloud™ Hyper Protect Crypto Services is a cloud hardware security module (HSM).```
I'm not sure if it is considered a cloud HSM or a cloud HSM service? I'll leave it up to you just thought I'd bring it to your attention.

**Comment by rossheninger** [comment]
@liuxjep

**Comment by liuxjep** [comment]
@rossheninger Hi Ross, thank you for spotting this! Yes, I agree, it's weird. I think your proposal `IBM Cloud™ Hyper Protect Crypto Services is a dedicated key management and cloud hardware security module (HSM) service.` is good, or we can make it aligned with the **Summary** in the **About** page (see https://github.ibm.com/ZaaS/zcrypto-backlog/issues/1195) to be `IBM Cloud™ Hyper Protect Crypto Services is a dedicated Key Management Service (KMS) and Hardware Security Module (HSM) service.`

However, the marketing page (https://www.ibm.com/cloud/hyper-protect-crypto) is owned by the marketing team, so we need Sowmya's review to get it finalized and also her help to get it published. Tiffany and I will contact Sowmya and keep you updated here. Thanks again. :)

**Comment by TiffanyLiIBM** [comment]
Hi Ross @rossheninger,

Thanks for letting us know this issue. We have let Sowmya know about this change requirement, and she will work with the marketing team to make the updates. Below please find her reply:

![Image from iOS](https://user-images.githubusercontent.com/40377681/73330525-f5d59200-429b-11ea-962e-07a62d0d40df.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/40377681/73330540-0259ea80-429c-11ea-904e-c6e5483c2819.png)

Since this issue is not doc related, I am going to close this issue from the doc repo.
