### ISSUE TITLE
Granting access to Vaults

### ISSUE THREAD

**Issue by sandeep-at-ibm** [ibm-cloud-docs/hs-crypto#43]
In the Doc https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-grant-access-vaults

Step-2, Sub-Step 7, 
- `Vault ID` attribute does not appear in the `Attribute Type` drop-down

What should be selected instead? The options that I see are:
- KeyRing ID
- Region
- Resource ID
- Resource Type
- Resource Group

**Comment by TiffanyLiIBM** [comment]
@sandeep-at-ibm Thanks for bringing this to our attention. It seems the options have changed. I am checking with the dev team and will make updates to the doc accordingly. 
https://ibm-cloudplatform.slack.com/archives/C02GL8GAR0B/p1675307978218049

**Comment by sandeep-at-ibm** [comment]
thanks @TiffanyLiIBM

**Comment by TiffanyLiIBM** [comment]
@sandeep-at-ibm It seems to be a bug with IAM rather than any changes made from the HPCS side. Heidi is now following up on this. Please find more details in: https://ibm-cloudplatform.slack.com/archives/C3C46LY7N/p1675798636959239.

I am going to close this issue if there is no other doc change needed. Thanks!

**Comment by TiffanyLiIBM** [comment]
An issue was opened in the backlog repo to track the dev effort: https://github.ibm.com/ZaaS/zcrypto-backlog/issues/7614.
It has now been fixed, thus closing this issue as well...
