### ISSUE TITLE
There isn't a KMS keys section on my UI

### ISSUE THREAD

**Issue by djp3** [ibm-cloud-docs/hs-crypto#53]
I can't follow this instruction:

"On the KMS keys page, use the Keys table to browse the keys in your service."

![Screenshot 2023-12-27 at 16 53 38](https://github.com/ibm-cloud-docs/hs-crypto/assets/121683/9931d587-fa0e-49c3-b935-1a54a5fa7899)

**Comment by TiffanyLiIBM** [comment]
@djp3 Hello-
Thanks for reaching out! From the screenshot you provided, I gathered you are using a UKO instance. Please check out the following doc for the instructions: 
[Viewing a list of managed keys](https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-view-key-list&interface=ui)
[Editing managed key details](https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-edit-kms-keys&interface=ui)

The content you were referring to applies to the Standard Plan only. If you have further questions, Please let me know. Thanks!

**Comment by djp3** [comment]
My problem was that I needed the CRN for my HPCS managed Key so that I could enter it into the VSI creation wizard.  So your links above *do* describe the HPCS interface... thank you... but it doesn't solve my problem which is locating my keys by CRN.
I'll attach the screen shot that shows what I'm trying to do:
![Screenshot 2023-12-29 at 22 07 41](https://github.com/ibm-cloud-docs/hs-crypto/assets/121683/8268b604-1ed1-4cb0-9b98-079463b84091)

**Comment by TiffanyLiIBM** [comment]
A CRN is associated with an HPCS instance instead of a key. For details on retrieving your instance CRN, see https://cloud.ibm.com/docs/hs-crypto?topic=hs-crypto-retrieve-instance-ID&interface=cli.
And I see how you were redirected to the Viewing key details page. I will contact the dev team to fix it. 

I am the content owner for the HPCS documentation. For further VSI related info, you can refer to: https://cloud.ibm.com/docs/vpc?topic=vpc-creating-virtual-servers&interface=ui.
