### ISSUE TITLE
Lack of useful error message in the UI when deleting service instance

### ISSUE THREAD

**Issue by dprosper** [ibm-cloud-docs/hs-crypto#6]
when deleting the Crypto Services, I get:

![image](https://user-images.githubusercontent.com/11874942/74668719-cff12e00-5173-11ea-8bf9-7eccd0d01cef.png)

I have to look at the console to find the real problem: "details: "[{"description":"There are still domains configured with a master key. Use the IBM Cloud CLI tke plugin to zeroize the domains.","error":"HsmStateError"}]""

![image](https://user-images.githubusercontent.com/11874942/74668746-dc758680-5173-11ea-9cc2-8cc5dd2dd7aa.png)

**Comment by embrown-ibm** [comment]
@dprosper The error that you experienced in your scenario will look like the following in our new implementation...

![image](https://user-images.githubusercontent.com/25669267/76952114-faedaf80-68e2-11ea-9d26-6cd9a1108838.png)

**Comment by embrown-ibm** [comment]
@dprosper My above screenshot is what happens when a user attempts to delete a key and gets an error.  But the scenario you described is a bit different.

There currently is an issue being worked on by our development team to handle the situation in which an instance of HPCS is deleted when the HSM has already been successfully configured.

**Comment by TiffanyLiIBM** [comment]
Close this issue as it will be addressed by the new design
